### ISSUE TITLE
Program execution continues but does not show any action on running main.py

### ISSUE THREAD

**Issue by parthlathiya2697** [SamanKhamesian/Human-Activity-Recognition-Time-Series-Classification#2]
Inside the file lstm.py, within the function `fit()` inside class `LSTMModel`, program does not show any update or anything. Just keeps executing endlessly.

What could have been the issue?

The final look into terminal
`/home/dnk025/Downloads/Time-Series-Classification-for-Human-Activity-Recognition-main/main.py 
LSTM network is running ...
Dataset Loaded Successfully!
2021-05-11 15:13:45.143392: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)`

Thanks in advance.

**Comment by SamanKhamesian** [comment]
Hi,
I actually use the built-in fit function from the Sequential() model. So, it just calculates and then returns the final result. This application usually takes a long time to process, but on my system (MacBook Pro MLH32, 2.6 GHz Quad-Core Intel Core i7, and 16 GB Memory), it takes about 10 minutes.
For the error you get, I think the issue comes from the TensorFlow and graphics card configuration. I rerun the application, and here is my output result. I didn't use Cuda to run the program on GPU. Hope I could help.

<img width="608" alt="Screen Shot 1400-02-21 at 21 25 05" src="https://user-images.githubusercontent.com/16573950/117855075-5d4fff00-b29f-11eb-854a-0b20c4d65dd2.png">
